// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: hello/v1/hello.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on HelloReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *HelloReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HelloReq with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in HelloReqMultiError, or nil
// if none found.
func (m *HelloReq) ValidateAll() error {
	return m.validate(true)
}

func (m *HelloReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return HelloReqMultiError(errors)
	}

	return nil
}

// HelloReqMultiError is an error wrapping multiple validation errors returned
// by HelloReq.ValidateAll() if the designated constraints aren't met.
type HelloReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HelloReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HelloReqMultiError) AllErrors() []error { return m }

// HelloReqValidationError is the validation error returned by
// HelloReq.Validate if the designated constraints aren't met.
type HelloReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HelloReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HelloReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HelloReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HelloReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HelloReqValidationError) ErrorName() string { return "HelloReqValidationError" }

// Error satisfies the builtin error interface
func (e HelloReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHelloReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HelloReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HelloReqValidationError{}

// Validate checks the field values on HelloResp with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *HelloResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HelloResp with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in HelloRespMultiError, or nil
// if none found.
func (m *HelloResp) ValidateAll() error {
	return m.validate(true)
}

func (m *HelloResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Message

	if len(errors) > 0 {
		return HelloRespMultiError(errors)
	}

	return nil
}

// HelloRespMultiError is an error wrapping multiple validation errors returned
// by HelloResp.ValidateAll() if the designated constraints aren't met.
type HelloRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HelloRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HelloRespMultiError) AllErrors() []error { return m }

// HelloRespValidationError is the validation error returned by
// HelloResp.Validate if the designated constraints aren't met.
type HelloRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HelloRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HelloRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HelloRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HelloRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HelloRespValidationError) ErrorName() string { return "HelloRespValidationError" }

// Error satisfies the builtin error interface
func (e HelloRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHelloResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HelloRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HelloRespValidationError{}
